Repository effective-tech-interview/effective-tech-interview-client, pull requests merged in 2023-02, with the labels that each got.

#1 settings: 프로젝트 설정 추가
  .eslintrc.json
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pr-labeler.config.yml
  .github/workflows/CI.yml
  .github/workflows/pr-labeler.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc.json
  commitlint.config.js
  labels.json
  mock-server/.gitignore
  mock-server/package.json
  mock-server/pnpm-lock.yaml
  mock-server/src/db.json
  mock-server/src/routes.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pnpm-lock.yaml
  src/apis/client.ts
  src/components/common/GlobalErrorFallback/GlobalErrorFallback.tsx
  src/components/common/GlobalErrorFallback/index.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/PretendardVariable.woff2
  src/components/common/Layout/index.ts
  src/components/common/QueryClientProvider/QueryClientProvider.tsx
  src/components/common/QueryClientProvider/index.tsx
  src/components/common/QueryErrorBoundary/QueryErrorBoundary.tsx
  src/components/common/QueryErrorBoundary/index.tsx
  src/components/common/RecoilDebugObserver/RecoilDebugObserver.tsx
  src/components/common/RecoilDebugObserver/index.tsx
  src/components/common/Text/Text.tsx
  src/components/common/Text/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/GlobalStyle/index.ts
  src/styles/GlobalStyle/reset.ts
  src/styles/Theme/Theme.ts
  src/styles/Theme/emotion.d.ts
  src/styles/Theme/index.ts
  tsconfig.json
Labels: Priority: Critical, Setting

#2 feat: input 컴포넌트 구현
  .prettierrc
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/common/Input/index.tsx
  src/pages/index.tsx
Labels: Type: Feature

#3 feat: icon 컴포넌트 구현
  next.config.js
  package.json
  pnpm-lock.yaml
  src/components/common/Icon/icons.ts
  src/components/common/Icon/icons/check.svg
  src/components/common/Icon/icons/downArrow.svg
  src/components/common/Icon/icons/hide.svg
  src/components/common/Icon/icons/leftArrow.svg
  src/components/common/Icon/icons/reload.svg
  src/components/common/Icon/icons/rightArrow.svg
  src/components/common/Icon/icons/setting.svg
  src/components/common/Icon/icons/show.svg
  src/components/common/Icon/icons/toGoHome.svg
  src/components/common/Icon/icons/upArrow.svg
  src/components/common/Icon/icons/user.svg
  src/components/common/Icon/index.tsx
Labels: Type: Feature

#5 feat: jest, react-testing-library setting
  jest.config.js
  jest.setup.js
  package.json
  pnpm-lock.yaml
  src/components/common/Text/Text.tsx
  src/pages/index.tsx
  tests/index/__snapshots__/index.test.tsx.snap
  tests/index/index.test.tsx
  tsconfig.json
Labels: Type: Feature

#7 feat: select 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/common/Select/Select.tsx
  src/components/common/Select/index.ts
  src/hooks/useCategorySelect.ts
  src/hooks/useDidMount.ts
  src/hooks/useDidUpdate.ts
  src/hooks/useWillUnmount.ts
  src/pages/index.tsx
  src/store/selectedCategoryId/index.ts
  src/store/selectedCategoryId/selectedCategoryIdAtom.ts
  src/types/index.ts
  src/types/response.d.ts
  src/types/types.ts
Labels: Type: Feature

#9 feat: header 컴포넌트 구현
  src/components/common/Header/index.tsx
  src/components/common/Layout/Layout.tsx
  src/pages/index.tsx
Labels: Type: Feature

#10 feat: sign up 레이아웃과 로직 구현
  package.json
  pnpm-lock.yaml
  src/apis/index.ts
  src/components/common/ConfirmModal/index.tsx
  src/constants/validationPattern.ts
  src/hooks/form/useCheckSignUpForm.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/password/[email]/index.tsx
Labels: Type: Feature

#11 refactor: button 컴포넌트 리팩토링
  src/components/common/Button/Button.tsx
  src/constants/button.ts
  src/styles/GlobalStyle/reset.ts
  src/styles/Theme/Theme.ts
Labels: Type: Refactor
