Repository effective-tech-interview/effective-tech-interview-client, pull requests merged in 2023-03, with the labels that each got.

#14 feat: toast component 구현
  package.json
  pnpm-lock.yaml
  src/components/common/ConfirmModal/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Toast/index.tsx
  src/hooks/useToast.tsx
  src/pages/login/index.tsx
Labels: Type: Feature

#13 feat: login
  src/apis/client.ts
  src/apis/index.ts
  src/hooks/form/useCheckLoginForm.ts
  src/hooks/form/useCheckSignUpForm.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/password/[email]/index.tsx
Labels: Type: Feature

#16 feat: 답변 Bubble 컴포넌트 구현
  src/components/common/AIBubble/index.tsx
Labels: Type: Feature

#17 feat: user answer bubble 컴포넌트 구현
  src/components/common/UserBubble/index.tsx
Labels: Type: Feature

#18 feat: input bubble 컴포넌트 구현
  src/components/common/InputBubble/index.tsx
Labels: Type: Feature

#21 feat: toast design system 적용
  src/components/common/Icon/icons.ts
  src/components/common/Icon/icons/warning.svg
  src/components/common/Toast/index.tsx
  src/pages/index.tsx
Labels: Type: Feature

#20 setting: test CI 및 codecov 부착
  .github/workflows/CI.yml
  codecov.yml
  package.json
Labels: Setting

#23 feat: 비밀번호 재설정 api fetching
  src/__tests__/utils/testUtils.tsx
  src/apis/index.ts
  src/components/common/HomeHeader/index.tsx
  src/components/signup/SignUpModal.tsx/index.tsx
  src/hooks/form/useCheckLoginForm.ts
  src/hooks/form/useCheckSignUpForm.tsx
  src/hooks/useShowLoginModal.tsx
  src/pages/find/[email]/index.tsx
  src/pages/find/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
Labels: Type: Feature

#24 feat: category 페이지 구현
  .gitignore
  src/__tests__/components/common/SingleBottomFixedButton.test.tsx
  src/__tests__/utils/renderSingleBottomFixedButton.tsx
  src/apis/client.ts
  src/apis/index.ts
  src/components/common/Button/BottomFixedButton.tsx
  src/components/common/Button/index.ts
  src/components/common/ClientSuspense/ClientSuspense.tsx
  src/components/common/ClientSuspense/index.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Select/Select.tsx
  src/constants/queryKeys.ts
  src/hooks/common/useDidMount.ts
  src/hooks/common/useDidUpdate.ts
  src/hooks/common/useMounted.ts
  src/hooks/common/useWillUnmount.ts
  src/hooks/form/useCheckLoginForm.ts
  src/hooks/query/useMainCategoryQuery.ts
  src/hooks/useBackgroundColor.ts
  src/hooks/useCategorySelect.ts
  src/pages/_app.tsx
  src/pages/category/[categoryId]/index.tsx
  src/pages/category/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#25 feat: category detail 페이지 구현
  next.config.js
  src/apis/index.ts
  src/components/categoryDetail/CategoryDetailBody.tsx
  src/components/categoryDetail/CategoryDetailHeader.tsx
  src/components/categoryDetail/index.ts
  src/constants/queryKeys.ts
  src/hooks/query/useMidCategoryQuery.ts
  src/pages/_app.tsx
  src/pages/category/[categoryId]/index.tsx
  src/pages/category/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#26 feat: question 페이지 구현
  next.config.js
  src/apis/index.ts
  src/components/categoryDetail/CategoryDetailBody.tsx
  src/components/categoryDetail/CategoryDetailHeader.tsx
  src/components/common/Button/BottomFixedButton.tsx
  src/components/common/InputBubble/index.tsx
  src/constants/queryKeys.ts
  src/hooks/query/useMainCategoriesQuery.ts
  src/hooks/query/useMainCategoryQuery.ts
  src/hooks/query/useMidCategoriesQuery.ts
  src/hooks/query/useMidCategory.ts
  src/hooks/query/useMidCategoryQuery.ts
  src/hooks/query/useRandomQuestionQuery.ts
  src/hooks/useBackgroundColor.ts
  src/pages/category/[categoryId]/index.tsx
  src/pages/category/index.tsx
  src/pages/questions/[categoryId]/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#27 feat: onboarding page 작업 완료
  src/components/common/HomeHeader/index.tsx
  src/pages/index.tsx
Labels: Type: Feature

#28 feat: chip component 구현
  src/components/common/Chip/index.tsx
Labels: Type: Feature

#30 test: Icon 컴포넌트 테스트 추가
  __mocks__/svg.js
  jest.config.js
  src/__tests__/components/common/Icon.test.tsx
  src/__tests__/utils/renderIcon.tsx
  src/components/common/Icon/icons.ts
Labels: Type: Test

#31 feat: question answer 기능 구현
  src/apis/index.ts
  src/components/common/Button/BottomFixedButton.tsx
  src/components/common/Button/index.ts
  src/constants/queryKeys.ts
  src/hooks/query/useQuestionAnswerQuery.ts
  src/pages/questions/[categoryId]/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#32 feat: token refetch 로직 추가
  package.json
  pnpm-lock.yaml
  src/apis/client.ts
  src/apis/index.ts
  src/components/common/SSRSuspense/index.tsx
  src/hooks/form/useCheckLoginForm.ts
  src/pages/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#34 feat: analytics tools 추가
  src/hooks/useAnalytics.ts
  src/pages/_app.tsx
  src/utils/gtag.ts
Labels: Type: Feature

#33 feat: mypage 작업 완료
  src/apis/client.ts
  src/apis/index.ts
  src/components/mypage/LogoutModal/index.tsx
  src/components/signup/SignUpModal/index.tsx
  src/constants/queryKeys.ts
  src/hooks/form/useCheckSignUpForm.tsx
  src/hooks/query/useUserInfoQuery.ts
  src/pages/mypage/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#37 feat: question 페이지 구현 v2
  src/apis/index.ts
  src/components/question/Question.tsx
  src/components/question/index.ts
  src/constants/queryKeys.ts
  src/hooks/mutation/useSaveQuestionAnswerMutation.ts
  src/hooks/query/usePagesQuery.ts
  src/hooks/query/useQuestionsQuery.ts
  src/hooks/query/useRandomQuestionQuery.ts
  src/pages/questions/[categoryId]/index.tsx
  src/types/response.d.ts
Labels: Type: Feature

#39 refactor: AIBubble 변경된 디자인 적용
  src/apis/index.ts
  src/components/common/AIBubble/index.tsx
  src/styles/Theme/Theme.ts
Labels: Type: Refactor

#40 feat: 헤더 변경 및 favicon, og tag 적용
  package.json
  pnpm-lock.yaml
  src/apis/index.ts
  src/components/common/Button/BottomFixedButton.tsx
  src/components/common/Header/index.tsx
  src/components/common/Icon/icons/rightArrow.svg
  src/components/common/Icon/index.tsx
  src/components/question/GoBackModal.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/category/[categoryId]/index.tsx
Labels: Type: Feature

#41 feat: responsive 디자인 적용
  src/components/common/Button/BottomFixedButton.tsx
  src/components/common/Layout/Layout.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/Theme/Theme.ts
Labels: Type: Feature

#42 setting: auto release tag action 추가
  .github/workflows/auto-release-tag.yml
  package.json
Labels: Setting

#44 hotfix: Release 1.0.0 deploy error 해결
  next.config.js
  src/components/common/Header/index.tsx
  src/hooks/query/usePagesQuery.ts
  src/hooks/query/useQuestionAnswerQuery.ts
  src/hooks/useModal.tsx
  src/hooks/useShowLoginModal.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: Type: Bug

#45 fix: auto release tag action permissions 추가
  .github/workflows/auto-release-tag.yml
Labels: Type: Bug

#47 fix: modal dimmed z-index 에러 해결
  src/hooks/useModal.tsx
Labels: Type: Bug

#48 fix: production url로 변경
  src/apis/client.ts
  src/apis/index.ts
Labels: Type: Bug

#57 style: input style 변경
  src/components/common/AIBubble/index.tsx
  src/components/common/InputBubble/index.tsx
  src/components/common/UserBubble/index.tsx
Labels: Type: Style

#58 feat: onboarding page 변경
  src/components/common/Chip/index.tsx
  src/components/common/HomeHeader/index.tsx
  src/pages/category/[categoryId]/index.tsx
  src/pages/index.tsx
Labels: Type: Feature

#60 style: layout 수정 및 scrollbar display none
  src/components/common/Layout/Layout.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: Type: Style
